CREATE TABLE `keyword_alerts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` VARCHAR(255) NOT NULL,
  `keyword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  INDEX `IDX_d03fb91772937997f010466a00` (`author`),
  FULLTEXT INDEX `post_title_fulltext_idx` (`title`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `post_id` INT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `deletedAt` DATETIME(6) NULL,
  `parent_id` INT NULL,
  INDEX `IDX_259bf9825d9d198608d1b46b0b` (`post_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_259bf9825d9d198608d1b46b0b5` FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB;
